#!/bin/bash
DATE=$(date +"%Y_%m_%d_%H")
OUTPUT_FILE=gwan_output.txt
TIME_INTERVAL_SECONDS=300
 
while true
do

        date >>/tmp/$OUTPUT_FILE
        fping -q -u -f ips.txt -c30 >>/tmp/$OUTPUT_FILE 2>&1
sleep $TIME_INTERVAL_SECONDS
done 
